name: RLTaskOffloading
channels:
  - defaults
dependencies:
  - certifi=2020.6.20
  - pip=21.2.2
  - python=3.6.13
  - setuptools=58.0.4
  - sqlite=3.36.0
  - pip:
    - absl-py==1.0.0
    - astor==0.8.1
    - cached-property==1.5.2
    - cloudpickle==2.0.0
    - dataclasses==0.8
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.42.0
    - gym==0.21.0
    - h5py==3.1.0
    - importlib-metadata==4.8.2
    - joblib==1.1.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.3.6
    - mpi4py==3.1.2
    - numpy==1.19.5
    - opt-einsum==3.3.0
    - protobuf==3.19.1
    - pydotplus==2.0.2
    - pyparsing==3.0.6
    - six==1.16.0
    - tensorboard==1.15.0
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.0
    - termcolor==1.1.0
    - typing-extensions==4.0.0
    - werkzeug==2.0.2
    - wrapt==1.13.3
    - zipp==3.6.0